### ISSUE TITLE
Reopen

### ISSUE THREAD

**Issue by souviiksarkar** [ssantanuberaa/Vidhikarya-HelpDesk#1]
Reopen a request not working

**Comment by ssantanuberaa** [comment]
Please leave a Comment If you need Help to assign a user on this thread

**Comment by souviiksarkar** [comment]
Need help from @ssantanuberaa

**Comment by ssantanuberaa** [comment]
The component "reopen" in **Component.js** is not doing anything. The ReopenRequest method is empty. So we need to write appropriate statement what we want to achieve in this method.

**Comment by souviiksarkar** [comment]
the reopenRequest will change the status of the request from closed to assigned. The assign lawyer will be the same lawyer who was involved in his/her request. And it will send an sms to the lawyer for reference.

**Comment by ssantanuberaa** [comment]
My Local Development is not Updated Yet. Please let me update it first and then i'll be able to work on this matter. Better off we continue this thread tomorrow

**Comment by souviiksarkar** [comment]
Ok.. then lets do this tomorrow..

**Comment by ssantanuberaa** [comment]
My Local Development is set up successfully. I'm working on this. Please tell me what data do you need to send to the server to reopen the request

**Comment by souviiksarkar** [comment]
the reopen button will change the status of the request from **closed** to **assigned.** And it will send an sms to the lawyer.

**Comment by ssantanuberaa** [comment]
Okay thank you. Work is in progress.

**Comment by ssantanuberaa** [comment]
Whom to Send SMS? Lawyer or Client?

**Comment by souviiksarkar** [comment]
Both of them. you just keep there a lorem ipsum text. I will change sms template.

**Comment by ssantanuberaa** [comment]
Okay...

**Comment by ssantanuberaa** [comment]
What happened when the success message returned after reopening. Page reload?

**Comment by souviiksarkar** [comment]
yes.

**Comment by ssantanuberaa** [comment]
Done
## Changed Files
1. views/Pages/Home.blade.php
1. js/Components.js
1. views/Layouts/Master.blade.php
1. app/Http/Controllers/HomeController.php

**Comment by ssantanuberaa** [comment]
Let me test

**Comment by souviiksarkar** [comment]
ok..and after testing, send me those files.

**Comment by ssantanuberaa** [comment]
We have another bug, The reopen form has a disabled text box but it is not getting populated by currently assigned lawyer email id.

**Comment by souviiksarkar** [comment]
yes. I just saw the disabled text box. Can we have a dropdown for lawyers. So we can change the assigned lawyer from there.

**Comment by ssantanuberaa** [comment]
It is fixed. And also created an API. I have listed the changed files. Please Download and update your local, environment. I cannot test in local as SMS doesn't work on local environment. Please test this in live and let me know when to commit the changes

**Comment by souviiksarkar** [comment]
send me the changed files

**Comment by ssantanuberaa** [comment]
The files are in the github code. Please check

**Comment by souviiksarkar** [comment]
Yes. Its working fine. Thanks. I will let you know if any problem occurs here.

**Comment by ssantanuberaa** [comment]
The sms won't go if you don't check the sms box. Did you test that

**Comment by ssantanuberaa** [comment]
Okay... Closing the issue... Issue a new thread if you find anthing
